'use client';

import { FormEvent, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check } from 'lucide-react';
import { Logo } from '@/components/Logo';
import { useLocale } from '@/components/LocaleProvider';

const statusQuestions = [
  ['information_security_policies','سياسات أمن المعلومات','Information security policies'],
  ['risk_register','سجل مخاطر','Risk register'],['periodic_audits','تدقيق دوري','Periodic audits'],
  ['evidence_repository','مستودع أدلة ووثائق','Evidence/document repository'],['control_owners','ملاك محددون للضوابط','Assigned control owners'],
  ['regulatory_tracking','متابعة للمتطلبات التنظيمية','Regulatory requirements tracking'],['existing_assessments','تقييمات امتثال سابقة','Existing compliance assessments'],
] as const;
const objectiveOptions = [
  ['assess','تقييم الوضع الحالي','Assess current compliance'],['regulatory','الاستعداد للمتطلبات التنظيمية','Prepare for regulatory requirements'],
  ['certification','الاستعداد لشهادة','Prepare for certification'],['policies','بناء السياسات والإجراءات','Build policies and procedures'],
  ['controls','إدارة الضوابط','Manage controls'],['risks','إدارة المخاطر','Manage risks'],['evidence','جمع الأدلة','Collect evidence'],
  ['audit','الاستعداد للتدقيق','Prepare for audit'],['indicators','متابعة مؤشرات الامتثال','Track compliance indicators'],['executive','لوحة تنفيذية','Executive dashboard'],
] as const;

type FormState = Record<string, string | boolean | string[] | Record<string,string>>;

export default function NewOrganizationPage(){
  const{locale,setLocale,tr}=useLocale();const router=useRouter();const[step,setStep]=useState(1);const[saving,setSaving]=useState(false);const[error,setError]=useState('');
  const[data,setData]=useState<FormState>({name_ar:'',name_en:'',organization_type:'university',sector:'education',country:'Saudi Arabia',city:'Riyadh',website:'',employee_size:'201-1000',primary_contact:'',entity_type:'government',handles_personal_data:true,handles_sensitive_data:false,critical_infrastructure:false,provides_digital_services:true,uses_cloud:true,has_cybersecurity_department:true,has_grc_team:true,has_branches:false,seeks_iso_certification:false,existing_certifications:[],current_status:{},objectives:['assess','regulatory','policies','evidence','audit']});
  const progress=step*20;const update=(key:string,value:FormState[string])=>setData(current=>({...current,[key]:value}));
  const steps=useMemo(()=>[tr('معلومات المؤسسة','Organization'),tr('السياق التنظيمي','Regulatory context'),tr('الوضع الحالي','Current status'),tr('الأهداف','Objectives'),tr('المراجعة','Review')],[tr]);
  function next(event?:FormEvent){event?.preventDefault();setError('');if(step===1&&(!data.name_ar||!data.name_en||!data.city)){setError(tr('أكمل الحقول المطلوبة.','Complete the required fields.'));return}setStep(value=>Math.min(5,value+1))}
  async function create(){setSaving(true);setError('');try{const profile={entity_type:data.entity_type,sector:data.sector,handles_personal_data:data.handles_personal_data,handles_sensitive_data:data.handles_sensitive_data,critical_infrastructure:data.critical_infrastructure,provides_digital_services:data.provides_digital_services,uses_cloud:data.uses_cloud,has_cybersecurity_department:data.has_cybersecurity_department,has_grc_team:data.has_grc_team,has_branches:data.has_branches,seeks_iso_certification:data.seeks_iso_certification,employee_size:data.employee_size,existing_certifications:data.existing_certifications,current_status:data.current_status,objectives:data.objectives};const response=await fetch('/api/backend/onboarding/organization',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name_ar:data.name_ar,name_en:data.name_en,organization_type:data.organization_type,country:data.country,city:data.city,website:data.website,primary_contact:data.primary_contact,profile})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.detail??tr('تعذر إنشاء المؤسسة.','Unable to create organization.'));router.replace('/workspace');router.refresh()}catch(reason){setError(reason instanceof Error?reason.message:tr('تعذر إنشاء المؤسسة.','Unable to create organization.'))}finally{setSaving(false)}}
  const input='mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal';
  return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><Logo/><button onClick={()=>setLocale(locale==='ar'?'en':'ar')} className="rounded-xl border px-3 py-2 text-xs font-bold">{locale==='ar'?'EN':'عربي'}</button></div></header><div className="mx-auto max-w-5xl px-5 py-10"><div className="mb-8"><span className="eyebrow">{tr('إعداد مساحة المؤسسة','Organization workspace setup')}</span><h1 className="mt-2 text-3xl font-black">{tr('أنشئ مؤسستك','Create your organization')}</h1><p className="mt-2 text-slate-600">{tr('نستخدم هذه المعلومات لاقتراح رحلات للمراجعة، وليس لإصدار حكم قانوني تلقائي.','We use this information to recommend journeys for review, not to make automatic legal determinations.')}</p></div><div className="mb-8 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-emerald-600 transition-all" style={{width:`${progress}%`}}/></div><ol className="mb-8 grid grid-cols-5 gap-2">{steps.map((label,index)=><li key={label} className={`text-center text-[11px] font-bold ${index+1<=step?'text-emerald-800':'text-slate-400'}`}><span className={`mx-auto mb-2 grid h-8 w-8 place-items-center rounded-full ${index+1<step?'bg-emerald-600 text-white':index+1===step?'border-2 border-emerald-600 bg-white':'bg-slate-200'}`}>{index+1<step?<Check className="h-4 w-4"/>:index+1}</span>{label}</li>)}</ol><section className="card p-6 md:p-8">
  {step===1?<form onSubmit={next} className="grid gap-5 md:grid-cols-2"><h2 className="text-xl font-black md:col-span-2">{tr('معلومات المؤسسة الأساسية','Basic organization information')}</h2>{[['name_ar',tr('اسم المؤسسة بالعربية','Organization name in Arabic')],['name_en',tr('اسم المؤسسة بالإنجليزية','Organization name in English')],['city',tr('المدينة','City')],['website',tr('الموقع الإلكتروني','Website')],['primary_contact',tr('جهة الاتصال الرئيسية','Primary contact')]].map(([key,label])=><label key={key} className="text-sm font-bold">{label}{key!=='website'&&key!=='primary_contact'?' *':''}<input required={key!=='website'&&key!=='primary_contact'} dir={key==='name_en'||key==='website'?'ltr':undefined} value={String(data[key])} onChange={e=>update(key,e.target.value)} className={input}/></label>)}<label className="text-sm font-bold">{tr('نوع المؤسسة','Organization type')}<select value={String(data.organization_type)} onChange={e=>update('organization_type',e.target.value)} className={input}><option value="government">{tr('جهة حكومية','Government entity')}</option><option value="university">{tr('جامعة / تعليم','University / Education')}</option><option value="company">{tr('شركة','Company')}</option><option value="healthcare">{tr('رعاية صحية','Healthcare')}</option><option value="financial">{tr('مؤسسة مالية','Financial institution')}</option><option value="non_profit">{tr('غير ربحي','Nonprofit')}</option><option value="other">{tr('أخرى','Other')}</option></select></label><label className="text-sm font-bold">{tr('القطاع','Sector')}<input value={String(data.sector)} onChange={e=>update('sector',e.target.value)} className={input}/></label><label className="text-sm font-bold">{tr('الدولة','Country')}<input value={String(data.country)} onChange={e=>update('country',e.target.value)} className={input}/></label><label className="text-sm font-bold">{tr('حجم المؤسسة','Organization size')}<select value={String(data.employee_size)} onChange={e=>update('employee_size',e.target.value)} className={input}>{['1-50','51-200','201-1000','1001-5000','5000+'].map(x=><option key={x}>{x}</option>)}</select></label><div className="md:col-span-2 flex justify-end"><button className="rounded-xl bg-emerald-700 px-6 py-3 font-black text-white">{tr('التالي','Next')}</button></div></form>:null}
  {step===2?<div><h2 className="text-xl font-black">{tr('السياق التنظيمي','Regulatory context')}</h2><p className="mt-2 text-sm text-slate-500">{tr('أجب بلغة الأعمال؛ لا تحتاج لمعرفة أسماء الأطر.','Answer in business terms; framework knowledge is not required.')}</p><div className="mt-6 grid gap-3 md:grid-cols-2">{[['handles_personal_data','تعالج بيانات شخصية','Handles personal data'],['handles_sensitive_data','تعالج بيانات شخصية حساسة','Handles sensitive personal data'],['critical_infrastructure','تشغّل بنية تحتية حرجة','Operates critical infrastructure'],['provides_digital_services','تقدم خدمات رقمية','Provides digital services'],['uses_cloud','لديها أحمال أو خدمات سحابية','Uses cloud workloads'],['has_cybersecurity_department','لديها إدارة أمن سيبراني','Has a cybersecurity department'],['has_grc_team','لديها فريق امتثال أو GRC','Has a compliance/GRC team'],['has_branches','لديها فروع أو جهات تابعة','Has branches or subsidiaries'],['seeks_iso_certification','تسعى لشهادة ISO','Seeking ISO certification']].map(([key,ar,en])=><label key={key} className="flex items-center justify-between rounded-xl border p-4 text-sm font-bold"><span>{tr(ar,en)}</span><input type="checkbox" checked={Boolean(data[key])} onChange={e=>update(key,e.target.checked)} className="h-5 w-5"/></label>)}</div></div>:null}
  {step===3?<div><h2 className="text-xl font-black">{tr('الوضع الحالي للامتثال','Current compliance status')}</h2><div className="mt-6 space-y-3">{statusQuestions.map(([key,ar,en])=><label key={key} className="grid items-center gap-3 rounded-xl border p-4 md:grid-cols-[1fr_220px]"><span className="text-sm font-bold">{tr(ar,en)}</span><select value={(data.current_status as Record<string,string>)[key]??'unknown'} onChange={e=>update('current_status',{...(data.current_status as Record<string,string>),[key]:e.target.value})} className="rounded-xl border px-3 py-2"><option value="yes">{tr('نعم','Yes')}</option><option value="partially">{tr('جزئياً','Partially')}</option><option value="no">{tr('لا','No')}</option><option value="unknown">{tr('غير متأكد','Unknown')}</option></select></label>)}</div></div>:null}
  {step===4?<div><h2 className="text-xl font-black">{tr('كيف تريد أن يساعدك ملتزم؟','How should Multazim help?')}</h2><p className="mt-2 text-sm text-slate-500">{tr('اختر أكثر من هدف.','Select all relevant objectives.')}</p><div className="mt-6 grid gap-3 md:grid-cols-2">{objectiveOptions.map(([value,ar,en])=>{const selected=(data.objectives as string[]).includes(value);return <label key={value} className={`flex items-center gap-3 rounded-xl border p-4 text-sm font-bold ${selected?'border-emerald-500 bg-emerald-50':''}`}><input type="checkbox" checked={selected} onChange={()=>update('objectives',selected?(data.objectives as string[]).filter(x=>x!==value):[...(data.objectives as string[]),value])} className="h-5 w-5"/>{tr(ar,en)}</label>})}</div></div>:null}
  {step===5?<div><h2 className="text-xl font-black">{tr('راجع معلومات مؤسستك','Review your organization')}</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{[['الاسم','Name',`${data.name_ar} / ${data.name_en}`],['النوع','Type',String(data.organization_type)],['القطاع','Sector',String(data.sector)],['الموقع','Location',`${data.city}, ${data.country}`],['الحجم','Size',String(data.employee_size)],['الأهداف','Objectives',String((data.objectives as string[]).length)]].map(([ar,en,value])=><div key={ar} className="rounded-xl bg-slate-50 p-4"><div className="text-xs font-bold text-slate-500">{tr(ar,en)}</div><div className="mt-1 font-black">{value}</div></div>)}</div><p className="mt-6 rounded-xl bg-blue-50 p-4 text-sm leading-6 text-blue-900">{tr('ستظهر الأطر كتوصيات للمراجعة، ويجب تأكيد الانطباق من مختص مؤهل.','Frameworks will be shown as recommendations for review; applicability must be confirmed by a qualified specialist.')}</p></div>:null}
  {error?<p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-800">{error}</p>:null}{step>1?<div className="mt-8 flex justify-between"><button onClick={()=>setStep(v=>v-1)} className="rounded-xl border px-5 py-3 font-bold">{tr('السابق','Back')}</button>{step<5?<button onClick={()=>next()} className="rounded-xl bg-emerald-700 px-6 py-3 font-black text-white">{tr('التالي','Next')}</button>:<button onClick={create} disabled={saving} className="rounded-xl bg-emerald-700 px-6 py-3 font-black text-white disabled:opacity-60">{saving?tr('جارٍ الإنشاء...','Creating...'):tr('إنشاء المؤسسة','Create organization')}</button>}</div>:null}
  </section></div></main>}
