'use client';

import { useEffect, useMemo, useState } from 'react';
import { AppShell } from '@/components/AppShell';
import { useLocale } from '@/components/LocaleProvider';
import { browserApiUrl, demoHeaders } from '@/lib/api';
import { useOrganizationId } from '@/components/SessionProvider';

type Campaign={id:string;title:string;framework_code:string;framework_version:string;scope:string;state:string};
type Evidence={id:string;title:string;state:string;expiry_date?:string};
type Control={code:string;domainAr:string;domainEn:string;titleAr:string;titleEn:string;demo:boolean};
type Status='compliant'|'partially_compliant'|'non_compliant'|'not_assessed'|'not_applicable';

const controls:Control[]=[
  {code:'DEMO-GOV-01',domainAr:'الحوكمة',domainEn:'Governance',titleAr:'اعتماد نطاق وأدوار برنامج الامتثال',titleEn:'Approve compliance program scope and roles',demo:true},
  {code:'DEMO-IAM-01',domainAr:'إدارة الوصول',domainEn:'Access management',titleAr:'مراجعة الحسابات ذات الصلاحيات العالية',titleEn:'Review privileged accounts',demo:true},
  {code:'DEMO-EVD-01',domainAr:'إدارة الأدلة',domainEn:'Evidence management',titleAr:'التحقق الدوري من صلاحية الأدلة',titleEn:'Periodically verify evidence validity',demo:true},
];
const statusOptions:[Status,string,string][]=[
  ['compliant','ممتثل','Compliant'],['partially_compliant','ممتثل جزئيًا','Partially compliant'],
  ['non_compliant','غير ممتثل','Non-compliant'],['not_assessed','لم يُقيّم','Not assessed'],['not_applicable','غير منطبق','Not applicable'],
];

async function api(path:string,init?:RequestInit){const response=await fetch(`${browserApiUrl()}${path}`,{...init,headers:{...demoHeaders,...init?.headers}});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.detail??`Request failed (${response.status})`);return response}

export default function Assessment(){
  const {locale,tr,formatNumber}=useLocale();const ar=locale==='ar';
  const {organizationId,loading:sessionLoading}=useOrganizationId();
  const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [evidence,setEvidence]=useState<Evidence[]>([]);const [active,setActive]=useState<Campaign|null>(null);
  const [control,setControl]=useState(controls[0]);const [status,setStatus]=useState<Status>('not_assessed');const [rationale,setRationale]=useState('');const [comment,setComment]=useState('');const [evidenceId,setEvidenceId]=useState('');
  const [title,setTitle]=useState('2026 readiness assessment');const [scope,setScope]=useState('Technology and information security');const [assessor,setAssessor]=useState('demo-assessor');
  const [search,setSearch]=useState('');const [saved,setSaved]=useState<Record<string,Status>>({});const [score,setScore]=useState<{readiness:number|null;assessment_completeness:number}|null>(null);
  const [state,setState]=useState<'loading'|'idle'|'saving'|'error'>('loading');const [message,setMessage]=useState('');
  const filtered=useMemo(()=>controls.filter(item=>`${item.code} ${item.titleAr} ${item.titleEn}`.toLowerCase().includes(search.toLowerCase())),[search]);
  const progress=Math.round(Object.keys(saved).length/controls.length*100);
  useEffect(()=>{if(sessionLoading||!organizationId)return;Promise.all([api('/v1/assessments').then(r=>r.json()),api('/v1/evidence').then(r=>r.json())]).then(([a,e])=>{setCampaigns(a);setEvidence(e);if(a[0])setActive(a[0]);setState('idle')}).catch(error=>{setMessage(error.message);setState('error')})},[organizationId,sessionLoading]);
  async function start(){if(!organizationId)return;setState('saving');setMessage('');try{const response=await api('/v1/assessments',{method:'POST',body:JSON.stringify({organization_id:organizationId,framework_code:'NCA-ECC-2-2024',framework_version:'2-2024',title,scope,assessor_ids:[assessor]})});const item=await response.json();setCampaigns(current=>[item,...current]);setActive(item);setState('idle')}catch(error){setMessage(error instanceof Error?error.message:String(error));setState('error')}}
  async function saveResponse(){if(!active)return;setState('saving');setMessage('');try{await api(`/v1/assessments/${active.id}/responses/${control.code}`,{method:'PUT',body:JSON.stringify({control_code:control.code,status,rationale,comment,evidence_ids:evidenceId?[evidenceId]:[],review_state:'submitted',mandatory:control.code==='DEMO-GOV-01',weight:control.code==='DEMO-GOV-01'?2:1})});setSaved(current=>({...current,[control.code]:status}));const result=await api(`/v1/assessments/${active.id}/score`).then(r=>r.json());setScore(result);setState('idle')}catch(error){setMessage(error instanceof Error?error.message:String(error));setState('error')}}
  async function createGapAndAction(){if(!active||!organizationId)return;setState('saving');try{const gap=await api('/v1/gaps',{method:'POST',body:JSON.stringify({organization_id:organizationId,assessment_id:active.id,framework_code:active.framework_code,control_code:control.code,finding:rationale||tr('يتطلب المتطلب معالجة موثقة.','The control requires documented remediation.'),current_state:comment,target_state:tr('تشغيل الضابط وتوثيق الدليل.','Operate the control and document evidence.'),severity:'high',risk:tr('قد يؤثر القصور على الجاهزية.','The deficiency may affect readiness.'),owner:assessor,due_date:'2026-09-30',remediation_plan:tr('معالجة القصور ثم تقديم دليل للمراجعة.','Remediate the deficiency and submit evidence for review.')})}).then(r=>r.json());await api('/v1/actions',{method:'POST',body:JSON.stringify({organization_id:organizationId,gap_id:gap.id,title:tr(`معالجة ${control.titleAr}`,`Remediate ${control.titleEn}`),description:rationale,owner:assessor,due_date:'2026-09-30',priority:'high',impacted_frameworks:[active.framework_code],completion_evidence_ids:[]})});setMessage(tr('تم إنشاء الفجوة وإجراء المعالجة.','Gap and remediation action created.'));setState('idle')}catch(error){setMessage(error instanceof Error?error.message:String(error));setState('error')}}
  async function downloadReport(){try{const response=await api(`/v1/reports/executive.pdf?locale=${locale}`);const url=URL.createObjectURL(await response.blob());const anchor=document.createElement('a');anchor.href=url;anchor.download=`multazim-executive-${locale}.pdf`;anchor.click();URL.revokeObjectURL(url)}catch(error){setMessage(error instanceof Error?error.message:String(error));setState('error')}}
  if(state==='loading')return <AppShell title={tr('التقييمات','Assessments')}><div className="card p-8" role="status">{tr('جارٍ تحميل التقييمات...','Loading assessments...')}</div></AppShell>;
  return <AppShell title={tr('مساحة عمل التقييم','Assessment workspace')}><div className="space-y-5">
    <section className="card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">{tr('رحلة مؤسستك','Your organization journey')}</p><h2 className="mt-1 text-xl font-black">{tr('تقييم الجاهزية الأولي','Initial readiness assessment')}</h2><p className="mt-1 text-sm text-slate-500">{tr('الضوابط الظاهرة أدناه أمثلة غير متحقق منها إلى أن يتم ربط الكتالوج التنظيمي المعتمد.','The controls below are unverified examples until the approved regulatory catalog is connected.')}</p></div><div className="min-w-52"><div className="flex justify-between text-xs font-bold"><span>{tr('تقدم التقييم','Assessment progress')}</span><span>{formatNumber(progress)}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-600" style={{width:`${progress}%`}}/></div></div></div></section>
    {!active?<section className="card p-6"><h2 className="text-xl font-black">{tr('بدء تقييم جديد','Start a new assessment')}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">{tr('العنوان','Title')}<input value={title} onChange={e=>setTitle(e.target.value)} required className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><label className="text-sm font-bold">{tr('النطاق','Scope')}<input value={scope} onChange={e=>setScope(e.target.value)} required className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><label className="text-sm font-bold">{tr('المقيّم','Assessor')}<input value={assessor} onChange={e=>setAssessor(e.target.value)} required className="mt-2 w-full rounded-xl border p-3 font-normal"/></label></div><button onClick={start} disabled={!title||!scope||!assessor||state==='saving'} className="mt-5 rounded-xl bg-slate-950 px-5 py-3 font-black text-white disabled:opacity-50">{tr('بدء التقييم','Start assessment')}</button>{campaigns.length===0?<p className="mt-4 text-sm text-slate-500">{tr('لا توجد تقييمات بعد. ابدأ أول تقييم جاهزية.','No assessments yet. Start the first readiness assessment.')}</p>:null}</section>:
    <div className="grid gap-5 xl:grid-cols-[300px_1fr_300px]"><aside className="card p-4"><label className="text-xs font-bold">{tr('بحث في الضوابط','Search controls')}<input value={search} onChange={e=>setSearch(e.target.value)} placeholder={tr('الرمز أو العنوان','Code or title')} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><div className="mt-4 space-y-2">{filtered.map(item=><button key={item.code} onClick={()=>{setControl(item);setStatus(saved[item.code]??'not_assessed')}} className={`w-full rounded-xl border p-3 text-start ${control.code===item.code?'border-emerald-500 bg-emerald-50':'border-slate-200'}`}><span className="block text-[10px] font-bold text-amber-700">DEMO / UNVERIFIED</span><b className="mt-1 block text-sm">{ar?item.titleAr:item.titleEn}</b><span className="text-[10px] text-slate-500" dir="ltr">{item.code}</span></button>)}</div></aside>
    <section className="card p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="eyebrow">{ar?control.domainAr:control.domainEn}</p><h2 className="mt-2 text-2xl font-black">{ar?control.titleAr:control.titleEn}</h2><code className="mt-2 block text-xs" dir="ltr">{control.code}</code></div><select aria-label={tr('حالة الضابط','Control status')} value={status} onChange={e=>setStatus(e.target.value as Status)} className="h-fit rounded-xl border p-3">{statusOptions.map(([value,a,e])=><option key={value} value={value}>{ar?a:e}</option>)}</select></div><div className="mt-6 grid gap-4"><label className="text-sm font-bold">{tr('المبرر','Rationale')}<textarea value={rationale} onChange={e=>setRationale(e.target.value)} required rows={4} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><label className="text-sm font-bold">{tr('ملاحظات المقيّم','Assessor comments')}<textarea value={comment} onChange={e=>setComment(e.target.value)} rows={3} className="mt-2 w-full rounded-xl border p-3 font-normal"/></label><label className="text-sm font-bold">{tr('إعادة استخدام دليل','Reuse evidence')}<select value={evidenceId} onChange={e=>setEvidenceId(e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"><option value="">{tr('بدون دليل','No evidence')}</option>{evidence.filter(item=>item.state!=='archived'&&item.state!=='rejected').map(item=><option key={item.id} value={item.id}>{item.title} - {item.state}</option>)}</select></label></div><div className="mt-5 flex flex-wrap gap-3"><button onClick={saveResponse} disabled={!rationale||state==='saving'} className="rounded-xl bg-emerald-700 px-5 py-3 font-black text-white disabled:opacity-50">{state==='saving'?tr('جارٍ الحفظ...','Saving...'):tr('حفظ التقدم','Save progress')}</button>{status==='non_compliant'||status==='partially_compliant'?<button onClick={createGapAndAction} className="rounded-xl border border-rose-300 px-5 py-3 font-black text-rose-800">{tr('إنشاء فجوة ومعالجة','Create gap and remediation')}</button>:null}</div></section>
    <aside className="card h-fit p-5"><h3 className="font-black">{tr('ملخص الجاهزية','Readiness summary')}</h3>{score?<><p className="mt-4 text-4xl font-black">{score.readiness===null?'—':`${formatNumber(score.readiness)}%`}</p><p className="mt-2 text-sm text-slate-500">{tr('اكتمال التقييم','Assessment completeness')}: {formatNumber(score.assessment_completeness)}%</p></>:<p className="mt-4 text-sm text-slate-500">{tr('احفظ أول استجابة لحساب نتيجة حقيقية.','Save the first response to calculate a real score.')}</p>}<button onClick={downloadReport} className="mt-5 w-full rounded-xl bg-slate-950 px-4 py-3 font-black text-white">{tr('إنشاء التقرير','Generate report')}</button><button onClick={()=>setActive(null)} className="mt-2 w-full rounded-xl border px-4 py-3 text-sm font-bold">{tr('العودة للتقييمات','Back to assessments')}</button></aside></div>}
    {message?<p role={state==='error'?'alert':'status'} className={`rounded-xl p-3 text-sm ${state==='error'?'bg-red-50 text-red-800':'bg-emerald-50 text-emerald-800'}`}>{message}</p>:null}
  </div></AppShell>;
}
