import {expect,test} from '@playwright/test';
import {onboardOrganization} from './auth-helper';

test('first-time organization journey persists and restores securely',async({page},testInfo)=>{
  test.setTimeout(120_000);
  const ar=testInfo.project.name.startsWith('ar-');
  const credentials=await onboardOrganization(page,testInfo,ar);
  await expect(page.locator('html')).toHaveAttribute('dir',ar?'rtl':'ltr');
  await page.reload();
  await expect(page.getByText(ar?'ابدأ رحلة الامتثال':'Start your compliance journey')).toBeVisible();
  await page.goto('/profile');
  await page.locator('input[name="mobile"]').fill('+966500000000');
  await page.locator('input[name="job_title"]').fill(ar?'مدير الالتزام':'Compliance Manager');
  await page.getByRole('button',{name:ar?'حفظ التغييرات':'Save changes'}).click();
  await expect(page.getByRole('status')).toContainText(ar?'تم حفظ الملف الشخصي':'Profile saved');
  await page.goto('/workspace');
  const recommended=page.getByText(ar?'رحلات موصى بمراجعتها':'Recommended journeys to review');
  await expect(recommended).toBeVisible();
  await page.goto('/assessment');
  const start=page.getByRole('button',{name:ar?'بدء التقييم':'Start assessment'});
  await expect(start).toBeVisible();
  await start.click();
  await page.getByLabel(ar?'حالة الضابط':'Control status').selectOption('partially_compliant');
  await page.getByLabel(ar?'المبرر':'Rationale').fill(ar?'توجد ضوابط جزئية وتتطلب استكمال التوثيق.':'Partial controls exist and documentation must be completed.');
  await page.getByRole('button',{name:ar?'حفظ التقدم':'Save progress'}).click();
  await expect(page.getByText(ar?'اكتمال التقييم':'Assessment completeness')).toBeVisible();
  await page.goto('/evidence');await expect(page.getByRole('button',{name:ar?'رفع دليل':'Upload evidence'})).toBeVisible();
  await page.goto('/gaps');await expect(page.locator('body')).not.toBeEmpty();
  await page.goto('/documents');await expect(page.locator('body')).not.toBeEmpty();
  await page.goto('/services');await expect(page.getByText('جامعة الإمام محمد بن سعود الإسلامية')).toBeVisible();
  await page.goto('/profile');await page.getByRole('button',{name:ar?'تسجيل الخروج':'Log out'}).click();
  await expect(page).toHaveURL(/\/$/);
  await page.goto('/workspace');await expect(page).toHaveURL(/\/sign-in/);
  await page.getByLabel(ar?'البريد الإلكتروني للعمل':'Work email').fill(credentials.email);
  await page.getByLabel(ar?'كلمة المرور':'Password').fill(credentials.password);
  await page.getByRole('button',{name:ar?'تسجيل الدخول':'Sign in'}).click();
  await expect(page).toHaveURL(/\/workspace/);
  await expect(page.getByRole('heading',{name:ar?'جامعة الإمام محمد بن سعود الإسلامية':'Imam Mohammad Ibn Saud Islamic University'})).toBeVisible();
});
