'use client';
import { useState } from 'react';
import { AppShell } from '@/components/AppShell';
import { StatusChip } from '@/components/StatusChip';
import { browserApiUrl,DEMO_ORGANIZATION_ID,demoHeaders } from '@/lib/api';

type Result={framework_code:string;name_ar:string;name_en:string;classification:string;reason_ar:string;source_url:string};
const questions=[['handles_personal_data','هل تعالج بيانات شخصية؟'],['handles_sensitive_data','هل تعالج بيانات شخصية حساسة؟'],['uses_cloud','هل تستخدم خدمات سحابية؟'],['provides_cloud_services','هل تقدم خدمات سحابية؟'],['sama_regulated','هل تخضع للبنك المركزي السعودي؟'],['cma_regulated','هل تخضع لهيئة السوق المالية؟'],['critical_systems','هل تشغل أنظمة حرجة؟'],['subject_to_e_invoicing','هل تخضع للفوترة الإلكترونية؟']] as const;
const tones:Record<string,'emerald'|'amber'|'blue'|'slate'>={MANDATORY:'emerald',LIKELY_APPLICABLE:'blue',CONDITIONAL:'amber',VOLUNTARY:'slate',NEEDS_REVIEW:'blue',NOT_APPLICABLE:'slate'};
const labels:Record<string,string>={MANDATORY:'إلزامي',LIKELY_APPLICABLE:'مرجح الانطباق',CONDITIONAL:'مشروط',VOLUNTARY:'طوعي',NEEDS_REVIEW:'مراجعة مطلوبة',NOT_APPLICABLE:'غير منطبق'};
export default function Universe(){
  const [profile,setProfile]=useState<Record<string,boolean>>({handles_personal_data:true,handles_sensitive_data:false,uses_cloud:true,provides_cloud_services:false,sama_regulated:false,cma_regulated:false,critical_systems:false,subject_to_e_invoicing:true});
  const [entityType,setEntityType]=useState('government');const [sector,setSector]=useState('technology');const [results,setResults]=useState<Result[]>([]);const [state,setState]=useState<'idle'|'saving'|'saved'|'error'>('idle');
  async function save(){setState('saving');const body={entity_type:entityType,sector,...profile};try{const base=browserApiUrl();const saved=await fetch(`${base}/v1/organizations/${DEMO_ORGANIZATION_ID}/profile`,{method:'PUT',headers:demoHeaders,body:JSON.stringify(body)});if(!saved.ok)throw new Error();const response=await fetch(`${base}/v1/organizations/${DEMO_ORGANIZATION_ID}/applicability`,{headers:demoHeaders});if(!response.ok)throw new Error();setResults(await response.json() as Result[]);setState('saved')}catch{setState('error')}}
  return <AppShell title="نطاق الامتثال الخاص بي"><div className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><section className="card p-6"><h2 className="text-lg font-black">ملف الجهة</h2><p className="mt-1 text-sm text-slate-500">احفظ الملف لتوليد نتيجة مفسرة من محرك الانطباق.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">نوع الجهة<select value={entityType} onChange={e=>setEntityType(e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"><option value="government">حكومية</option><option value="semi_government">شبه حكومية</option><option value="private">خاصة</option><option value="non_profit">غير ربحية</option></select></label><label className="text-sm font-bold">القطاع<select value={sector} onChange={e=>setSector(e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"><option value="technology">تقنية</option><option value="finance">مالي</option><option value="healthcare">صحي</option><option value="education">تعليمي</option><option value="government">حكومي</option></select></label></div><div className="mt-5 space-y-3">{questions.map(([id,q])=><div key={id} className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><span className="text-sm font-bold">{q}</span><button type="button" aria-pressed={Boolean(profile[id])} onClick={()=>setProfile(p=>({...p,[id]:!p[id]}))} className={`rounded-full px-4 py-1.5 text-xs font-black ${profile[id]?'bg-emerald-700 text-white':'bg-slate-100 text-slate-500'}`}>{profile[id]?'نعم':'لا'}</button></div>)}</div><button onClick={save} disabled={state==='saving'} className="mt-5 w-full rounded-xl bg-emerald-700 px-5 py-3 font-black text-white disabled:opacity-60">{state==='saving'?'جارٍ التحليل...':'حفظ وتوليد نطاق الامتثال'}</button>{state==='error'?<p role="alert" className="mt-3 text-sm text-red-700">تعذر الاتصال بالـ API. شغّل FastAPI على المنفذ 8000 ثم أعد المحاولة.</p>:null}</section><section className="space-y-3"><div><h2 className="text-lg font-black">النتيجة المفسرة</h2><p className="text-sm text-slate-500">كل قرار يوضح سبب الانطباق ومصدره الرسمي.</p></div>{results.length===0?<div className="card p-8 text-center text-sm text-slate-500">احفظ ملف الجهة لعرض الأطر المنطبقة.</div>:results.map(item=><article key={item.framework_code} className="card p-5"><div className="flex items-start justify-between gap-3"><div><b dir="ltr">{item.framework_code}</b><h3 className="mt-1 font-black">{item.name_ar}</h3><p className="text-xs text-slate-400">{item.name_en}</p></div><StatusChip tone={tones[item.classification]??'slate'}>{labels[item.classification]??item.classification}</StatusChip></div><p className="mt-3 text-sm leading-6 text-slate-600"><b>لماذا ينطبق؟</b> {item.reason_ar}</p><a className="mt-3 inline-block text-xs font-bold text-emerald-700 underline" href={item.source_url} target="_blank" rel="noreferrer">المصدر الرسمي</a></article>)}</section></div></AppShell>}
